"""domain_schema

Revision ID: 95a735a7c999
Revises: '0001_enable_postgis'
Create Date: 2026-08-02 16:39:00.305190

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '95a735a7c999'
down_revision: str | None = '0001_enable_postgis'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('license_identifier', sa.String(length=100), nullable=True),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'deprecated', name='source_status'), server_default='active', nullable=False),  # noqa: E501
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.CheckConstraint('length(trim(display_name)) > 0', name=op.f('ck_data_source_ck_data_source_display_name_nonempty')),  # noqa: E501
    sa.CheckConstraint('length(trim(key)) > 0', name=op.f('ck_data_source_ck_data_source_key_nonempty')),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source')),
    sa.UniqueConstraint('key', name='uq_data_source_key')
    )
    op.create_table('dataset_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_checksum', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'partial', name='snapshot_status'), server_default='pending', nullable=False),  # noqa: E501
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], name=op.f('fk_dataset_snapshot_data_source_id_data_source'), ondelete='RESTRICT'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_snapshot'))
    )
    op.create_index(op.f('ix_dataset_snapshot_data_source_id'), 'dataset_snapshot', ['data_source_id'], unique=False)  # noqa: E501
    op.create_table('locality',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('parent_zone', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),  # noqa: E501
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),  # noqa: E501
    sa.Column('geometry_source', sa.Enum('osm_polygon', 'osm_point', 'manual_curation', 'centroid_buffer', name='geometry_source'), nullable=True),  # noqa: E501
    sa.Column('geometry_confidence', sa.Enum('high', 'medium', 'low', 'insufficient', name='geometry_confidence'), nullable=True),  # noqa: E501
    sa.Column('external_source_id', sa.String(length=100), nullable=True),
    sa.Column('geometry_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_locality_ck_locality_name_nonempty')),  # noqa: E501
    sa.CheckConstraint('length(trim(slug)) > 0', name=op.f('ck_locality_ck_locality_slug_nonempty')),  # noqa: E501
    sa.CheckConstraint('slug = lower(slug)', name=op.f('ck_locality_ck_locality_slug_lowercase')),
    sa.ForeignKeyConstraint(['geometry_snapshot_id'], ['dataset_snapshot.id'], name=op.f('fk_locality_geometry_snapshot_id_dataset_snapshot'), ondelete='SET NULL'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locality')),
    sa.UniqueConstraint('slug', name='uq_locality_slug')
    )
    op.create_index('ix_locality_centroid', 'locality', ['centroid'], unique=False, postgresql_using='gist')  # noqa: E501
    op.create_index('ix_locality_geometry', 'locality', ['geometry'], unique=False, postgresql_using='gist')  # noqa: E501
    op.create_index(op.f('ix_locality_geometry_snapshot_id'), 'locality', ['geometry_snapshot_id'], unique=False)  # noqa: E501
    op.create_index('ix_locality_is_active', 'locality', ['is_active'], unique=False)
    op.create_table('locality_alias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locality_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('alias_lower', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.CheckConstraint('alias_lower = lower(alias_lower)', name=op.f('ck_locality_alias_ck_locality_alias_alias_lower_lowercase')),  # noqa: E501
    sa.CheckConstraint('length(trim(alias)) > 0', name=op.f('ck_locality_alias_ck_locality_alias_alias_nonempty')),  # noqa: E501
    sa.ForeignKeyConstraint(['locality_id'], ['locality.id'], name=op.f('fk_locality_alias_locality_id_locality'), ondelete='CASCADE'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locality_alias')),
    sa.UniqueConstraint('alias_lower', name='uq_locality_alias_alias_lower')
    )  # noqa: E501
    op.create_table('locality_metric',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locality_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_type', sa.Enum('cafe_density', 'restaurant_density', 'park_accessibility', 'healthcare_accessibility', 'metro_distance_m', 'metro_walk_distance_m', 'amenity_composite', name='metric_type'), nullable=False),  # noqa: E501
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('calc_version', sa.String(length=80), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', 'insufficient', name='metric_confidence'), nullable=False),  # noqa: E501
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.CheckConstraint('length(trim(calc_version)) > 0', name=op.f('ck_locality_metric_ck_locality_metric_calc_version_nonempty')),  # noqa: E501
    sa.ForeignKeyConstraint(['locality_id'], ['locality.id'], name=op.f('fk_locality_metric_locality_id_locality'), ondelete='CASCADE'),  # noqa: E501
    sa.ForeignKeyConstraint(['snapshot_id'], ['dataset_snapshot.id'], name=op.f('fk_locality_metric_snapshot_id_dataset_snapshot'), ondelete='SET NULL'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locality_metric')),
    sa.UniqueConstraint('locality_id', 'metric_type', 'calc_version', 'snapshot_id', name='uq_locality_metric_calc_version_snap')  # noqa: E501
    )
    op.create_index(op.f('ix_locality_metric_locality_id'), 'locality_metric', ['locality_id'], unique=False)  # noqa: E501
    op.create_index('ix_locality_metric_locality_id_metric_type', 'locality_metric', ['locality_id', 'metric_type'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_locality_metric_snapshot_id'), 'locality_metric', ['snapshot_id'], unique=False)  # noqa: E501
    op.create_table('locality_rent_observation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locality_id', sa.BigInteger(), nullable=False),
    sa.Column('housing_config', sa.Enum('rk_1', 'bhk_1', 'bhk_2', 'bhk_3', name='housing_configuration'), nullable=False),  # noqa: E501
    sa.Column('rent_min_inr', sa.Integer(), nullable=True),
    sa.Column('rent_max_inr', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('observed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', 'insufficient', name='metric_confidence'), nullable=False),  # noqa: E501
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),  # noqa: E501
    sa.CheckConstraint('length(trim(currency_code)) = 3', name=op.f('ck_locality_rent_observation_ck_locality_rent_observation_currency_len')),  # noqa: E501
    sa.CheckConstraint('rent_max_inr >= 0', name=op.f('ck_locality_rent_observation_ck_locality_rent_observation_rent_max_nonneg')),  # noqa: E501
    sa.CheckConstraint('rent_min_inr >= 0', name=op.f('ck_locality_rent_observation_ck_locality_rent_observation_rent_min_nonneg')),  # noqa: E501
    sa.CheckConstraint('rent_min_inr IS NOT NULL OR rent_max_inr IS NOT NULL', name=op.f('ck_locality_rent_observation_ck_locality_rent_observation_has_bound')),  # noqa: E501
    sa.CheckConstraint('rent_min_inr IS NULL OR rent_max_inr IS NULL OR rent_min_inr <= rent_max_inr', name=op.f('ck_locality_rent_observation_ck_locality_rent_observation_min_lte_max')),  # noqa: E501
    sa.CheckConstraint('sample_size IS NULL OR sample_size > 0', name=op.f('ck_locality_rent_observation_ck_locality_rent_observation_sample_positive')),  # noqa: E501
    sa.ForeignKeyConstraint(['locality_id'], ['locality.id'], name=op.f('fk_locality_rent_observation_locality_id_locality'), ondelete='CASCADE'),  # noqa: E501
    sa.ForeignKeyConstraint(['snapshot_id'], ['dataset_snapshot.id'], name=op.f('fk_locality_rent_observation_snapshot_id_dataset_snapshot'), ondelete='SET NULL'),  # noqa: E501
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locality_rent_observation'))
    )
    op.create_index(op.f('ix_locality_rent_observation_locality_id'), 'locality_rent_observation', ['locality_id'], unique=False)  # noqa: E501
    op.create_index('ix_locality_rent_observation_locality_id_housing_config', 'locality_rent_observation', ['locality_id', 'housing_config'], unique=False)  # noqa: E501
    op.create_index(op.f('ix_locality_rent_observation_snapshot_id'), 'locality_rent_observation', ['snapshot_id'], unique=False)  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locality_rent_observation_snapshot_id'), table_name='locality_rent_observation')  # noqa: E501
    op.drop_index('ix_locality_rent_observation_locality_id_housing_config', table_name='locality_rent_observation')  # noqa: E501
    op.drop_index(op.f('ix_locality_rent_observation_locality_id'), table_name='locality_rent_observation')  # noqa: E501
    op.drop_table('locality_rent_observation')
    op.drop_index(op.f('ix_locality_metric_snapshot_id'), table_name='locality_metric')
    op.drop_index('ix_locality_metric_locality_id_metric_type', table_name='locality_metric')
    op.drop_index(op.f('ix_locality_metric_locality_id'), table_name='locality_metric')
    op.drop_table('locality_metric')
    op.drop_table('locality_alias')
    op.drop_index('ix_locality_is_active', table_name='locality')
    op.drop_index(op.f('ix_locality_geometry_snapshot_id'), table_name='locality')
    op.drop_index('ix_locality_geometry', table_name='locality', postgresql_using='gist')
    op.drop_index('ix_locality_centroid', table_name='locality', postgresql_using='gist')
    op.drop_table('locality')
    op.drop_index(op.f('ix_dataset_snapshot_data_source_id'), table_name='dataset_snapshot')
    op.drop_table('dataset_snapshot')
    op.drop_table('data_source')
    op.execute("DROP TYPE IF EXISTS metric_type")
    op.execute("DROP TYPE IF EXISTS metric_confidence")
    op.execute("DROP TYPE IF EXISTS housing_configuration")
    op.execute("DROP TYPE IF EXISTS geometry_confidence")
    op.execute("DROP TYPE IF EXISTS geometry_source")
    op.execute("DROP TYPE IF EXISTS snapshot_status")
    op.execute("DROP TYPE IF EXISTS source_status")
    # ### end Alembic commands ###
