"""metro_intelligence

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-02 18:02:15.333749

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metro_station",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9-]+$'", name=op.f("ck_metro_station_ck_metro_station_slug_format")
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_metro_station_ck_metro_station_name_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dataset_snapshot.id"],
            name=op.f("fk_metro_station_snapshot_id_dataset_snapshot"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metro_station")),
    )
    op.create_index(
        op.f("ix_metro_station_is_active"), "metro_station", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_metro_station_slug"), "metro_station", ["slug"], unique=True)
    op.create_index(
        op.f("ix_metro_station_snapshot_id"), "metro_station", ["snapshot_id"], unique=False
    )
    op.add_column(
        "locality_metric",
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locality_metric", "extra_data")
    op.drop_index(op.f("ix_metro_station_snapshot_id"), table_name="metro_station")
    op.drop_index(op.f("ix_metro_station_slug"), table_name="metro_station")
    op.drop_index(op.f("ix_metro_station_is_active"), table_name="metro_station")
    op.drop_table("metro_station")
    # ### end Alembic commands ###
