"""add metro is_operational and line

Revision ID: 60753185ce9f
Revises: '0006'
Create Date: 2026-08-06 11:47:19.718617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60753185ce9f'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_amenity_poi_osm_id'), 'amenity_poi', type_='unique')
    op.drop_index(op.f('ix_amenity_poi_osm_id'), table_name='amenity_poi')
    op.create_index(op.f('ix_amenity_poi_osm_id'), 'amenity_poi', ['osm_id'], unique=True)
    op.create_index(op.f('ix_amenity_poi_geometry'), 'amenity_poi', ['geometry'], unique=False)
    op.add_column('metro_station', sa.Column('is_operational', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('metro_station', sa.Column('line', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_metro_station_geometry'), 'metro_station', ['geometry'], unique=False)
    op.create_index(op.f('ix_metro_station_is_operational'), 'metro_station', ['is_operational'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metro_station_is_operational'), table_name='metro_station')
    op.drop_index(op.f('ix_metro_station_geometry'), table_name='metro_station')
    op.drop_column('metro_station', 'line')
    op.drop_column('metro_station', 'is_operational')
    op.drop_index(op.f('ix_amenity_poi_geometry'), table_name='amenity_poi')
    op.drop_index(op.f('ix_amenity_poi_osm_id'), table_name='amenity_poi')
    op.create_index(op.f('ix_amenity_poi_osm_id'), 'amenity_poi', ['osm_id'], unique=False)
    op.create_unique_constraint(op.f('uq_amenity_poi_osm_id'), 'amenity_poi', ['osm_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
